application: radegastupdate
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /admin/.*
  script: admin.py
- url: /svc/.*
  script: svc.py
- url: .*
  script: main.py
